spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8081
logging:
  file:
    name: ./spring/spring-boot/spring-boot-web/target/spring.log
